### ISSUE TITLE
Xenoblades chronicles Max Money cheat still does not work 

### ISSUE THREAD

**Issue by deadmanbomber** [FlagBrew/Sharkive#134] opened 2019-03-15 14:25 UTC
I have seen that there already was a issue about this and was solved, but I am having this issue. I have updated the cheat list to see if it was outdated on my system, but it still has yet to work.

**Comment by deadmanbomber** [comment] 2019-03-15 14:29
I know that there is a work around to get easy money with one of the cheats on the same list, so I am not really bothered that the code is not functional. Up to you if you want to remove the code or just add a note to it.

**Comment by deadmanbomber** [comment] 2019-03-15 14:39
And before you ask, I have tried the Nightly build to see if that was the case.

**Comment by JourneyOver** [comment] 2019-03-15 15:16
All I can say is make sure your game is up to date or if your above the version required for the cheats then downgrade, as the codes are for version 1.1 of the game and you didn't mention a version or anything in your issue (which tbh is grounds for a closure anyway since you didn't follow the issue template at all)

There are still issues with the cheat engine in luma https://github.com/AuroraWright/Luma3DS/issues/1212 so it could be a case of this or it could even be a case of you have to be at a certain point in the game or do a specific thing for it to work (but I can't tell you what it would be if that's the case since I don't even know and there is no info pertaining to it anywhere), but since it's already been confirmed working for version 1.1 in the other issue you mention (which would of been nice if you actually linked it so I didn't have to go searching for it) then I am going to go ahead and close this.

**Closed by JourneyOver** 2019-03-15 15:16 UTC
