### ISSUE TITLE
smt 4 code making more null demon

### ISSUE THREAD

**Issue by aruna87** [FlagBrew/Sharkive#91] opened 2018-10-09 22:19 UTC
im new on this github though but smt 4(not smt 4 apocalypse) sharkive gateshark code not working
it making more null demon and fill the party slot

**Comment by JourneyOver** [comment] 2018-10-10 09:33
1. Please fill out the issue form otherwise this issue will be closed

2. You need to be a bit more specific on what the issue is, as currently I can barely make out what you are even saying.

3. Even though I barely make sense of this issue and you haven't filled out any information, please test with the latest Luma nightly.

**Comment by JourneyOver** [comment] 2018-10-13 05:20
Due to you not updating your issue to follow the issue template in a timely manner we will be closing the issue,  if you feel like we have made a mistake or you have updated the issue to use the template after closure then feel free to reopen the issue.

**Closed by JourneyOver** 2018-10-13 05:20 UTC
Labels: question
