### ISSUE TITLE
Cannot find other installed games

### ISSUE THREAD

**Issue by BryanJames16** [FlagBrew/Sharkive#150] opened 2019-04-20 13:50 UTC
### Fill this for problems with codes in the database

* **Platform (3DS/Switch)**: Old 3DS
* **Title ID**: 00086300
* **Luma version**: 9.1

### Error
While connected to the internet, I opened Sharkive. However, not all of my installed applications are being detected. I tried deleting tickets and titles and opened Sharkive again. This time, it detected some of my games (Animal Crossing New Leaf) for instance. Please note that this game already has saved files before I booted Sharkive.

**Comment by gregeh552** [comment] 2019-04-20 16:02
Same for me

**Comment by SpiredMoth** [comment] 2019-04-20 16:46
This seems like a duplicate of #21.

Make sure that the games you're trying to make appear really do have a save in them, delete the file `/3ds/Sharkive/titles.sha`, then boot Sharkive again.

If the above fix *doesn't* work for you, feel free to reopen with a description of everything you've tried. The app Sharkive is no longer going to receive updates, but we might be able to find a workaround that can be used until the next release of Checkpoint (Sharkive's cheat retrieval code is being integrated into it).

**Closed by SpiredMoth** 2019-04-20 16:46 UTC

**Comment by gregeh552** [comment] 2019-04-20 20:09
@SpiredMoth Thanks, this solved the issue for me. Is there a simple reason for this behavior?

**Comment by JourneyOver** [comment] 2019-04-20 20:18
Sharkive uses the same detection logic as Checkpoint: it only recognizes a title as a game if it finds a save in it, and it's using pretty old detection logic that is kinda buggy so it sometimes misses a title even if there is a save.

A lot of these problems with sharkive will go away when we get sharkives cheat retrieval code into checkpoint and fully deprecate sharkive.
