### ISSUE TITLE
Sharkive displays only one page of installed titles

### ISSUE THREAD

**Issue by kforney** [FlagBrew/Sharkive#60] opened 2018-08-02 11:04 UTC
## Issue template

* [X] Issue with Sharkive
* [] Issue with one or more codes in the database

### Fill this for problems with Sharkive (the app)

* **Expected behaviour**:
Sharkive displays all titles that are installed on the unit.

* **Encountered behavior**:
Sharkive only displays the first page of titles.  Any further pages are empty.

Unit: New 2DS XL
Firmware Version: 11.8.0-41U
Luma3DS Version: 9.1

**Comment by DragonautMk** [comment] 2018-09-29 10:08
I hope this bug will fixed soon...

**Comment by SpiredMoth** [comment] 2018-09-30 10:48
Sounds like this might be related to Sharkive not recognizing games without a save in them (intended behavior) and/or #21.

Try making sure there's a save in each game you want cheats for, then delete `/3ds/Sharkive/titles.sha` and reboot Sharkive.

**Comment by BSBussell** [comment] 2018-12-05 19:01
Should we close this issue as related to #21

**Comment by JourneyOver** [comment] 2018-12-05 22:17
The reason on why I haven't closed this yet is due to the fact that there is sometimes a small bug where you seem to be able to scroll through an infinite amount of blank pages, doesn't seem to always happen but it does happen from time to time.

**Comment by hexthat** [comment] 2019-06-14 18:27
all my tittles dont show up, only 29 in both checkpoint and sharkive, unable to switch pages in checkpoint or sharkive....

when i refresh in checkpoint the tittle i want shows up then after it refresh the list gets rearranged and it disappears

**Comment by piepie62** [comment] 2019-06-14 18:50
Try going left on the edge

**Comment by piepie62** [comment] 2019-06-14 18:50
Or maybe down, don't really remember TBH

**Closed by piepie62** 2019-06-14 18:50 UTC
Labels: bug
