### ISSUE TITLE
Pokemon super mystery dungeon cheats that aren’t working

### ISSUE THREAD

**Issue by OGBaggett** [FlagBrew/Sharkive#124] opened 2019-02-10 18:30 UTC
Cheats that are crashing

* fill my belly | crashes the 3ds
*max hp for slot 1 | crashes the 3ds
*max stats for all slots | only gives full HP
*max attack for slot 1 Pokemon | crashes the 3ds

Title ID: 00174600
* **Product code**: CTR-P-BPXE
* **Game version**: ver 1.0
* **Luma version**: v9.1-bd15f51a

### Not working codes

* Fill My Belly v1.0
* Max Stats for All Slots v1.0
* Max EXP for slots 1 through 3 v1.0

**Comment by OGBaggett** [comment] 2019-02-10 18:31
I will go ahead and add the note none of the codes work, these are the codes that I want to save your time. THANK YOU!

**Comment by JourneyOver** [comment] 2019-02-10 18:38
So a major thing...

Please fill out
```
* **Title ID**:
* **Product code**:
* **Game version**:
* **Luma version**:v9.1
```
like you are supposed to, otherwise this issue will be closed.

**Comment by OGBaggett** [comment] 2019-02-10 19:09
What do you mean by product code and where do I find it?

**Comment by JourneyOver** [comment] 2019-02-10 19:14
Product code is the thing that usually starts with CTR..you can find all this information (minus game version) in sharkive.

You will need to find out your game version some other way.

**Comment by OGBaggett** [comment] 2019-02-10 19:17
Found the product code thank you

**Comment by OGBaggett** [comment] 2019-02-10 19:56
I am currently using nightly so the codes didn’t work

**Comment by JourneyOver** [comment] 2019-02-10 20:07
Okay, they will be removed when either I have time to get around to it, which right now with irl stuff going on my time is very limited or if another member of the flagbrew team decides to remove them.

**Comment by OGBaggett** [comment] 2019-02-10 20:11
Okay don’t worry about it, thank you for the time you did have.

**Comment by ImMetatron** [comment] 2019-02-12 11:37
This does not work on any build.

**Comment by JourneyOver** [comment] 2019-02-17 07:57
Hmm so I took a look through the closed issues, as people have reported this game/TitleID before, and I had tested things before as noted here https://github.com/FlagBrew/Sharkive/issues/47#issuecomment-388521747 and all the codes you have reported I had confirmed was working on Version 1.0 of the game and codes don't magically just break when it's on the same version of the game that they are made for...

So I am closing this as it's a duplicate of #47 and as mentioned I have already confirmed them working before on Version 1.0 of the game.

**Closed by JourneyOver** 2019-02-17 07:57 UTC
Labels: WIP
