### ISSUE TITLE
[WIP] [EUR] DarkSide1305's Cheat Testing Notes

### ISSUE THREAD

**Issue by DarkSide1305** [FlagBrew/Sharkive#72] opened 2018-08-07 15:06 UTC
This is going to be a Big Issue of all the Codes I am available to test.

Every game is EU, with all DLC's and all Updates. 
EDIT: Also, EVERY game is digital

My DS in on 11.8, with the Luma boot.firm that JourneyOver posted into the Discord

Every game is going to have its own comment.

Also, im going to update this Issue when I have time to test Codes. I will remove the Games I have already tested from the List below, so you guys can know which games I am still going to test:

Hyrule Warriors Legends
Luigi's Mansion 2
Majoras Maks 3D
Mario & Luigi Dream Team Bros
Mario & Luigi Paper Jam Bros
Mario & Luigi Superstar Saga + Bowsers Minions
Mega Man Legacy Collection
Metroid: Samus Returns
Miitopia
New Super Mario Bros 2.
Ocarina of Time 3D
Paper Mario Sticker Star
Pokemon Alpha Sapphire
Pokemon Y
Pokemon Moon
Pokemon Ultra Moon
Super Street Fighter IV
Shantae and the Pirates Curse
Tri Force Heroes
Fire Emblem: Awakening
Pokemon Super Mystery Dungeon
BOXBOY!
Chibi-Robo! Zip Lash
FE Echoes: Shadows of Valentia
Fire Emblem Fates
MGS SNAKE EATER 3D
Monster Hunter 3 Ultimate
Monster Hunter 4 Ultimate
Monster Hunter Gen
Monster Hunter Stories
Mario & Sonic Rio 2016
Mario Party: Island Tour
Professor Layton - Miracle Mask
Professor Layton and the Azran Legacy
Professor Layton vs Phoenix Wright
Star Fox 64 3D
Tetris Ultimate
Wario Ware Gold

**Comment by DarkSide1305** [comment] 2018-08-07 15:22
Super Mario 3D Land:

Working:

Max Infinite TIme Rev02
Max Lives after losing 1 Rev02

Not working:

Lower Slot Tanooki Leaf (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot item Fire Flower (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot boomerang (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot P-Wings (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot Super Leaf (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot Item Mushroom (doesnt dont turn Red, but does nothing, or atleast not for me)
Lower Slot Item (doesnt turn Red, but I cant find a Key Combo)
Change item lowerslot (not working yet)  (the name says it all, I just put it here)
Invincibilyty W1
99 Coints (doesnt turn Red, but I cant find a Key Combo)
Invincible
Coordinates Modifier (turns Red and I cant find a Key Combo)
Slot Item Changer (doesnt turn red, but does nothing, or atleast not for me)
Max Coins (doesnt turn red, but I cant find a Key Combo)
Moon Jump (turns red and I cant find a Key Combo)

Codes we dont need anymore:

Infinite Time (we already have "Max Infinite TIme Rev02", no reason to have 2)
999 Lives (we already have "Max Lives after Losing 1 Rev02", no reason to have 2)
Save Slot 1 - 1110 lives (3 crowns)    (we already have "Max Lives after Losing 1 Rev 02", no reason to have 2)

**Comment by DarkSide1305** [comment] 2018-08-07 15:36
The Legend of Zelda: A Link beetween Worlds:

Working

Max Rupees
Max Monster Tails (removes Monster Guts?)
Max Monster Guts (removes Monster Horns?)
Max Monster Horns (removes MaiMais????? I dont know if thats really how it is, but on my 100% Save File It removed all MaiMais before it added the Monster Horns)
Max MaiMais
Full Hearts
Have 5 Dungeon Keys
Reset Ammount of Rubees
Invincible
Using Items doesn't cost energy
Money doesnt decrease
Being a painting doesnt decrease energy
Cucoo Ranch Minigame Easy Win (Hold R)


Not working:

Infinite Power Meter (I have the extended one, maybe that doesnt work? Might need more research. And, in theory we dont need that Code since Being a Painting doesnt decrease energy and using Items doesnt decrease Energy work just fine)

**Comment by DarkSide1305** [comment] 2018-08-07 15:46
Terraria

Working:

No working Codes :/

Not working:

Inf HP v1.0 (doesnt turn red but doesnt work)
Get HP MAX v1.0 (doesnt turn red but doesnt work)
Inf Oxygen v1.0 (doesnt turn red but doesnt work)
Inf Use Item v1.0 (doesnt turn red but doesnt work. I guess you can use something like Dirt infinite times? If thats that it should do, it doesnt work)
Get Item MAX v1.0 (doesnt turn red but doesnt work)
Instant Kill v1.0 (doesnt turn red but doesnt work)
003ED2E4 XXXXXXXX (I dont know what it does, but it seems like nothing?)

**Comment by DarkSide1305** [comment] 2018-08-07 20:11
Mario Kart 7

Working:

500cc Mode
200cc Mode

Not Working:

90000 Coins Collected, Rev0 v1.1 (doesnt turn red but doesnt work)
Mirror Mode, Rev0 v1.1 (doesnt turn red but doesnt work)
All Gliders, Rev0 v1.1 (doesnt turn red but doesnt work)
All Wheels, Rev0 v1.1 (doesnt turn red but doesnt work)
All Karts, Rev0 v1.1 (doesnt turn red but doesnt work)
All Courses, Rev0 v1.1 (doesnt turn red but doesnt work)
All Characters, Rev0 v1.1 (doesnt turn red but doesnt work)
Coin x 99,999 v1.1 Legit CIA w/ 1.1 Up (doesnt turn red but doesnt work)
Water Everywhere, Everytime (doesnt turn red but doesnt work)
Item Cacler Rev0 v.1.1 (turns red, I found a Video of an Item Cycler, tried that Key Combo and it didnt work. Couldnt find other Key Combos)
Moonjump (Hold X) (sometimes turns red, sometimes not, but it still doesnt work)
Infinite Ballons (battle) (turns red and doesnt work)
Gravity Modifier (doesnt turn red but doesnt work)
The Stalking Hack (turns red and I cant find a Key Combo)
The Stalking Hack 2.0 (X) (sometimes turns red, sometimes not, but it still doesnt work)
Hide Item Box Top Screen Icon - REGION (I think it should be disabeling the Icon on the Topscreen? Im not sure but it doesnt work, but doesnt turn red)
Invincible (doesnt turn red but doesnt work)
Always "Shooted" effect (doesnt turn red but doesnt work)
Always Slipstreaming Effect (doesnt turn red but doesnt work)
Can make jump boost everywhere (doesnt turn red but doesnt work)

Cant Test:

90000 Coins Collected, Game v1.0 (im on 1.1, so cant test)
Mirror Mode, Game v1.0 (im on 1.1, so cant test)
All Gliders, Game v1.0 (im on 1.1, so cant test)
All Wheels, Game v1.0 (im on 1.1, so cant test)
All Karts, Game v1.0 (im on 1.1, so cant test)
All Courses, Game v1.0 (im on 1.1, so cant test)
All Characters, Game v1.0 (im on 1.1, so cant test)
Coin x 99,999 v1.0 (im on 1.1, so cant test)
Balloons battle pts modifier rev0 1.1 (cant test because Im not sure if that can get me banned)
VR is 99,999 (rev0) (cant test because Im not sure if that can get me banned)
Battle Points Controllere (cant test because Im not sure if that can get me banned)
Region Changer (cant test because Im not sure if that can get me banned)

**Comment by DarkSide1305** [comment] 2018-08-11 08:48
Tomodachi Life

Working:

MAX MONEY L+UP v2.0

Not working:

50Re1/4 L+DOWN v2.0 (Name is broken so I cant say what it does, but it seems to take away my money)

Cant test:

MAX MONEX L+UP v1.0 (im on 2.0, so cant test)
50Re1/4 L+DOWN v1.0 (Name is broken, so I cant really test if it works. Also im on 2.0 so cant test)

**Comment by DarkSide1305** [comment] 2018-08-11 08:56
Super Mario Maker 3DS

Working:

10x Run Speed (Use D-Pad)
3x Run Speed (Use D-Pad)
2x Run Speed (Use D-Pad)
Press L+R+A+B To Kill yourself
Invincibility v1.04 (once turned on doesnt turn off)
Fly Straight Upwards (Softlock) (I guess it works as the Name says?)
Countdown Time from 500

Not working:

All Codes work :D

Cant test:

Score 999999990 v1.02 (im on 1.04, so cant test)

**Comment by DarkSide1305** [comment] 2018-08-11 09:11
Shovel Knight: Treasure Trove

Working:

None of the codes work :/

Not working:

Cant test any Codes, im on 3.2

Cant test:

Max Money, Game v1.2 (im on 3.2, so cant test)
Magic Max upgraded game v1.2 (im on 3.2, so cant test)
Life max upgraded game v1.2 (im on 3.2, so cant test)
Armor slot change item game 1.0 (im on 3.2, so cant test)

**Comment by DarkSide1305** [comment] 2018-08-11 11:01
Sonic Generations:

Working:

Freeze Timer
Max Rings
Max Lifes
Walk Through Enemies
Infinite Boost
Freeze Timer (Special Stages)
Infinite Oxygen

Not working:

All of the codes are working :D

**Comment by DarkSide1305** [comment] 2018-08-11 12:27
DK Country Returns 3D

Working:

Infinite Health, Slot1
Infinite Lives, Slot1
500 Banana Coins, Slot1
Infinite Inventory Items, Slot1
Have K O N G, Slot1
Invincible Golden, Slot1
Infinite Green Ballon Use, Slot1
Infinite DK Barrel
Every Slot2 Cheat Code
Every Slot3 Cheat Code

Not working:

All of the Codes work :D

**Comment by tstambaugh92** [comment] 2018-08-11 21:33
Can you try the Link Between Worlds cheat for infinite energy on the newest Luma nightly? I patched in something that should have fixed it. Was going to test those codes myself but you seem to have done it for me

**Comment by tstambaugh92** [comment] 2018-08-11 21:36
Also the Mario Kart 7 cheats might work. The red code means they were getting a bad address because the current stable Luma doesn't handle codes with pointers, but I corrected that issue as well.

**Comment by Sanaki** [comment] 2018-08-16 23:36
On latest Luma nightly, no Theatrhythm Curtain Call codes work -on save slot 2-. If I had to guess, using the second save slot is indeed what's screwing them all up, and that may be an issue worth watching out for on other games with multiple save slots. That said, when I get a bit more time I'll make a save backup and start a slot 1 save (reserved for my girlfriend) to test it out properly.

On a similar note, do any utilities exist currently for generating these codes ourselves on bs9/luma3ds? I haven't seen any myself yet, but I'd be more than happy to help repair some of the code lists if so.

**Comment by tstambaugh92** [comment] 2018-08-16 23:40
There is a program out there called TCP Gecko dot net that was made for wii u but modified for 3ds that let's you scan your 3ds memory from your laptop. It uses a custom version of NTR CFW to connect. It's kinda jank and buggy but it does work pretty well, it's what I have been using.

**Comment by agufungus** [comment] 2018-08-21 19:55
Can we add Kirby Triple Deluxe to this issue? None of the three available codes work. Version: U, eShop.

**Comment by kimstraza** [comment] 2018-08-26 06:02
Story of season:trio of town , food buff also seem to not work, no indication of it happening and the fantastic pet code too

**Comment by VeronicaDavichi** [comment] 2018-08-26 07:01
Persona Q (US): 
none of the codes work (including money, items, HP, SP, persona)
can't test: Levels of characters(I am all Lv99)
11.8.0, Luma 9.1, old 3DS

**Comment by tstambaugh92** [comment] 2018-08-26 07:10
Veronica, are you using the latest nightly build? The money, level, health, and sp may not work on the default 9.1 Luma if you activated the cheats before loading your save file.

**Comment by SpiredMoth** [comment] 2018-08-26 07:17
@Sanaki @agufungus @kimstraza @VeronicaDavichi Sorry for any confusion caused by the issue's title but this thread isn't meant to be a catch-all for reporting codes that do not work. Please open new issues, providing all the proper information on what codes do and/or do not work for you so your input doesn't get buried and we can check them properly, and remove them from the database if necessary.

@DarkSide1305 I've renamed this issue in an attempt to prevent the somewhat unrelated posts that are lacking the proper info from being made here and getting buried.

**Comment by JourneyOver** [comment] 2018-09-17 19:53
@DarkSide1305 just making sure you are still around and going to be working on this?

**Comment by DarkSide1305** [comment] 2018-09-17 20:07
@JourneyOver I dont think so. Sadly, I have far too much work with my last year of school, so I cant spend the time working on this '-'

**Comment by JourneyOver** [comment] 2018-09-17 21:09
Alright, I'll go through what you have done so far at least and remove broken codes and close this issue when I get my new computer and then if you ever decide to do this again you can just make a new issue in the future.

**Closed** 2018-12-06 01:41 UTC
Labels: WIP
