### ISSUE TITLE
problems with cheats in vc pokemon gold

### ISSUE THREAD

**Issue by EpicXboss250** [FlagBrew/Sharkive#278] opened 2021-07-12 01:46 UTC
I used cheats in pokemon gold virtual console on 3ds to get all the pokeballs and i got a bunch of light balls aswell i tried to sell them or throw them away but i still have them after, i turned off the cheat in the luma 3ds menu and even eventualy disabled them all in checkpoint and there still not able to be tossed. any answers as to what this is or how to solve it would be greatley appreciated.

**Comment by GriffinG1** [comment] 2022-08-23 04:30
This seems like an odd situational bug that may have been caused by a unique console environment. I'm going to close this for now, if anyone else comes across this bug, with proof, please follow up and the code will be removed.

**Closed by GriffinG1** 2022-08-23 04:30 UTC
